### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by honestree** [Ramotion/aquarelle#7]
Hi @Juriv,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team.we're going to host this library.
The git auto-update in cdnjs relies on [git tags](https://github.com/Ramotion/aquarelle/tags) so that it can recognized the correct version and automatically update this repo.
Could you please add git tags for the repo? Thank you.

https://github.com/cdnjs/cdnjs/issues/10310

**Comment by Juriv** [comment]
done, thanks
